version: "3.8"
services:
  suitecrm:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      # Add environment variables for API configuration
      - APACHE_HTTP_PORT_NUMBER=8080
      - APACHE_HTTPS_PORT_NUMBER=8443
    volumes:
      - suitecrm_data:/bitnami/suitecrm
    networks:
      - suitecrm-network
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - suitecrm-network

networks:
  suitecrm-network:

volumes:
  mariadb_data:
  suitecrm_data:
