version: "3.8"
services:
  suitecrm:
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_DATABASE_USER=bn_suitecrm
      - SUITECRM_DATABASE_PASSWORD=bitnami
      - SUITECRM_DATABASE_NAME=bitnami_suitecrm
      - SUITECRM_DATABASE_HOST=mariadb
      - APACHE_HTTP_PORT_NUMBER=8080
      - APACHE_HTTPS_PORT_NUMBER=8443
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M
    volumes:
      - suitecrm_data:/bitnami/suitecrm
      - ./oauth2:/bitnami/suitecrm/public/legacy/Api/V8/OAuth2
    networks:
      - suitecrm-network
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_suitecrm
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_suitecrm
    volumes:
      - mariadb_data:/bitnami/mariadb
    networks:
      - suitecrm-network

networks:
  suitecrm-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local