services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Extension\WebToMeeting\backend\Process\Service\CreateMeetingFromWebForm:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $security: '@security.helper'
            $logger: '@logger'
        tags: ['app.process.handler']